version: '2'

services:

    node:
        build:
            context: ./node
            args:
                - NODE_VERSION=latest
                - PROJECT_PATH=/opt/app/
                - NODE_ENV=production
        volumes:
            - ../:/opt/app
        extra_hosts:
            - "dockerhost:10.0.75.1"
        entrypoint: run-nodock "node index.js"
        tty: true

    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_DATABASE=default_database
                - MYSQL_USER=default_user
                - MYSQL_PASSWORD=secret
        volumes_from:
            - volumes
        expose:
            - "3306"
        extra_hosts:
            - "dockerhost:10.0.75.1"

    nginx:
        build:
            context: ./nginx
            args:
                - WEB_REVERSE_PROXY_PORT=8000
                - WEB_SSL=false
                - SELF_SIGNED=false
                - NO_DEFAULT=false
        volumes_from:
            - volumes
        ports:
            - "80:80"
            - "443:443"
        extra_hosts:
            - "dockerhost:10.0.75.1"
        tty: true

    certbot:
        build:
            context: ./certbot
        links:
            - nginx
        volumes_from:
            - volumes
            
    workspace:
        build:
            context: ./workspace
            args:
                - NODE_VERSION=latest
                - TZ=UTC
        links:
            - nginx
        volumes:
            - ../:/opt/app
        volumes_from:
            - volumes

    volumes:
        image: tianon/true
        volumes:
            - ./certbot/letsencrypt/:/var/www/letsencrypt
            - ./certbot/certs/:/var/certs
            - ./data/mysql:/var/lib/mysql
            - ./data/logs/nginx/:/var/log/nginx
