version: '2'

services:

    node:
        build:
            context: ./node
        volumes_from:
            - volumes_source
        extra_hosts:
            - "dockerhost:10.0.75.1"
        depends_on:
            - volumes_source
        command: bash -c 'export NVM_DIR="/root/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"; node -e "console.log(11111);"'

    workspace:
      build:
          context: ./workspace
      volumes_from:
          - volumes_source
      extra_hosts:
          - "dockerhost:10.0.75.1"
      ports:
         - "22:22"
      tty: true

    mysql:
        build:
            context: ./mysql
        volumes_from:
            - volumes_source
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: default_database
            MYSQL_USER: default_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

    nginx:
        build:
            context: ./nginx
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - node
        extra_hosts:
            - "dockerhost:10.0.75.1"
        tty: true

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/opt/app
