version: '2'

services:

    node:
        build:
            context: ./node
        volumes_from:
            - volumes
        extra_hosts:
            - "dockerhost:10.0.75.1"
        entrypoint: run-nodock "node index.js"
        environment:
            NODE_ENV: production
        tty: true

    mysql:
        build:
            context: ./mysql
        volumes_from:
            - volumes
        expose:
            - "3306"
        extra_hosts:
            - "dockerhost:10.0.75.1"
        environment:
            MYSQL_DATABASE: default_database
            MYSQL_USER: default_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

    nginx:
        build:
            context: ./nginx
            args:
                reverse_proxy_port: "8000"
        volumes_from:
            - volumes
        ports:
            - "80:80"
            - "443:443"
        links:
            - node
        extra_hosts:
            - "dockerhost:10.0.75.1"
        tty: true

    volumes:
        image: tianon/true
        volumes:
            - ../:/opt/app
            - ./data/logs/nginx/:/var/log/nginx
