# docker-compose.override.yml

version: '2'

services:
    node2: # name of new container
        extends: node # extends the settings from the "node" container
        build:
            context: ./node
            args:
                - PROJECT_PATH=second-app
        entrypoint: run-nodock "node index.js" # the entrypoint for the "node2" container
    nginx:
        ports:
            - "10000:10000" # the port(s) to forward for the "node2" container
        links:
            - node2 # link "nginx" to "node2"